- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: removing old containers
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm

    - name: pull image
      shell: docker pull divyamagwl/calculator:latest
      
    - name: run container
      shell: docker run -i -t --name calculator -d divyamagwl/calculator